# Actividad de Numpy

In [ ]:
#Importar numpy como primer paso
import numpy as np

In [ ]:
#Arreglo de 10 cincos
arreglo_cincos =np.full(10, 5)
print(arreglo_cincos)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#Arreglo de enteros pares desde 10, inclusive, hasta 50, inclusive
arreglo_de_enteros = np.arange (10,51,10)
print (arreglo_de_enteros)

[10 20 30 40 50]


In [ ]:
#Matriz cuadrada de 4 por 4 de números enteros aleatorios
matriz_aleatoria=np.random.randint(0, 100, size=(4, 4))
print(matriz_aleatoria)

[[87  1 86 20]
 [32 98 35 66]
 [53 30 63 13]
 [53 25 47 86]]


In [ ]:
#Arreglo de 10 números aleatorios entre 0 y 1 y calcula la suma de todos sus elementos
elementos=np.random.rand(10)
print(elementos)
print("suma")
print(np.sum(elementos))

[0.40588408 0.46350078 0.11989495 0.63055211 0.15873572 0.76720126
 0.22614522 0.02543442 0.56523137 0.36144287]
suma
3.724022773115374


In [ ]:
#Genera un arreglo de 10 números aleatorios entre 0 y 1 y calcula su media
elementos=np.random.rand(10)
print(elementos)
print("media")
print(np.mean(elementos))

[0.95911017 0.02643986 0.53246356 0.77835762 0.43586355 0.96160936
 0.64727264 0.8608536  0.62187775 0.99023124]
media
0.6814079369020672
